create table event (event_id varchar(255) not null, created_at datetime(6), updated_at datetime(6), event_capacity integer, event_name varchar(50), event_occupation integer, location varchar(20), time datetime(6), primary key (event_id)) engine=InnoDB;
create table event_ticket (event_id varchar(255) not null, created_at datetime(6), updated_at datetime(6), age integer, event_name varchar(255), name varchar(20), surname varchar(20), ticket_name varchar(255), ticket_price decimal(19,2), event_event_id varchar(255), primary key (event_id)) engine=InnoDB;
alter table event_ticket add constraint FK62jb9fygncc2j4jyfvtgwvupl foreign key (event_event_id) references event (event_id);

create table event (event_id varchar(255) not null, created_at datetime, updated_at datetime, event_capacity integer, event_name varchar(50), event_occupation integer, location varchar(20), time datetime, primary key (event_id)) engine=InnoDB
create table event_ticket (event_id varchar(255) not null, created_at datetime, updated_at datetime, age integer, event_name varchar(255), event_ticket_id varchar(255), name varchar(20), surname varchar(20), ticket_name varchar(255), ticket_price decimal(19,2), event_event_id varchar(255), primary key (event_id)) engine=InnoDB
alter table event_ticket add constraint FK62jb9fygncc2j4jyfvtgwvupl foreign key (event_event_id) references event (event_id)
create table event (event_id varchar(255) not null, created_at datetime, updated_at datetime, event_capacity integer, event_name varchar(50), event_occupation integer, location varchar(20), time datetime, primary key (event_id)) engine=InnoDB
create table event_ticket (event_id varchar(255) not null, created_at datetime, updated_at datetime, age integer, event_name varchar(255), event_ticket_id varchar(255), name varchar(20), surname varchar(20), ticket_name varchar(255), ticket_price decimal(19,2), event_event_id varchar(255), primary key (event_id)) engine=InnoDB
alter table event_ticket add constraint FK62jb9fygncc2j4jyfvtgwvupl foreign key (event_event_id) references event (event_id)
create table event (event_id varchar(255) not null, created_at datetime, updated_at datetime, event_capacity integer, event_name varchar(50), event_occupation integer, location varchar(20), time datetime, primary key (event_id)) engine=InnoDB
create table event_ticket (event_id varchar(255) not null, created_at datetime, updated_at datetime, age integer, event_name varchar(255), event_ticket_id varchar(255), name varchar(20), surname varchar(20), ticket_name varchar(255), ticket_price decimal(19,2), event_event_id varchar(255), primary key (event_id)) engine=InnoDB
alter table event_ticket add constraint FK62jb9fygncc2j4jyfvtgwvupl foreign key (event_event_id) references event (event_id)
create table event (event_id varchar(255) not null, created_at datetime, updated_at datetime, event_capacity integer, event_name varchar(50), event_occupation integer, location varchar(20), time datetime, primary key (event_id)) engine=InnoDB
create table event_ticket (event_id varchar(255) not null, created_at datetime, updated_at datetime, age integer, event_name varchar(255), event_ticket_id varchar(255), name varchar(20), surname varchar(20), ticket_name varchar(255), ticket_price decimal(19,2), event_event_id varchar(255), primary key (event_id)) engine=InnoDB
alter table event_ticket add constraint FK62jb9fygncc2j4jyfvtgwvupl foreign key (event_event_id) references event (event_id)
create table event (event_id varchar(255) not null, created_at datetime, updated_at datetime, event_capacity integer, event_name varchar(50), event_occupation integer, location varchar(20), time datetime, primary key (event_id)) engine=InnoDB
create table event_ticket (event_id varchar(255) not null, created_at datetime, updated_at datetime, age integer, event_name varchar(255), event_ticket_id varchar(255), name varchar(20), surname varchar(20), ticket_name varchar(255), ticket_price decimal(19,2), event_event_id varchar(255), primary key (event_id)) engine=InnoDB
alter table event_ticket add constraint FK62jb9fygncc2j4jyfvtgwvupl foreign key (event_event_id) references event (event_id)
create table event (event_id varchar(255) not null, created_at datetime, updated_at datetime, event_capacity integer, event_name varchar(50), event_occupation integer, location varchar(20), time datetime, primary key (event_id)) engine=InnoDB
create table event_ticket (event_id varchar(255) not null, created_at datetime, updated_at datetime, age integer, event_name varchar(255), event_ticket_id varchar(255), name varchar(20), surname varchar(20), ticket_name varchar(255), ticket_price decimal(19,2), event_event_id varchar(255), primary key (event_id)) engine=InnoDB
alter table event_ticket add constraint FK62jb9fygncc2j4jyfvtgwvupl foreign key (event_event_id) references event (event_id)
create table event (event_id varchar(255) not null, created_at datetime, updated_at datetime, event_capacity integer, event_name varchar(50), event_occupation integer, location varchar(20), time datetime, primary key (event_id)) engine=InnoDB
create table event_ticket (event_id varchar(255) not null, created_at datetime, updated_at datetime, age integer, event_name varchar(255), event_ticket_id varchar(255), name varchar(20), surname varchar(20), ticket_name varchar(255), ticket_price decimal(19,2), event_event_id varchar(255), primary key (event_id)) engine=InnoDB
alter table event_ticket add constraint FK62jb9fygncc2j4jyfvtgwvupl foreign key (event_event_id) references event (event_id)
create table event (event_id varchar(255) not null, created_at datetime, updated_at datetime, event_capacity integer, event_name varchar(50), event_occupation integer, location varchar(20), time datetime, primary key (event_id)) engine=InnoDB
create table event_ticket (event_id varchar(255) not null, created_at datetime, updated_at datetime, age integer, event_name varchar(255), event_ticket_id varchar(255), name varchar(20), surname varchar(20), ticket_name varchar(255), ticket_price decimal(19,2), event_event_id varchar(255), primary key (event_id)) engine=InnoDB
alter table event_ticket add constraint FK62jb9fygncc2j4jyfvtgwvupl foreign key (event_event_id) references event (event_id)
create table event (private_event_id varchar(255) not null, created_at datetime, updated_at datetime, event_capacity integer, event_id varchar(255), event_name varchar(50), event_occupation integer, location varchar(20), time datetime, primary key (private_event_id)) engine=InnoDB
create table event_ticket (private_event_id varchar(255) not null, created_at datetime, updated_at datetime, age integer, event_name varchar(255), event_ticket_id varchar(255), name varchar(20), surname varchar(20), ticket_name varchar(255), ticket_price decimal(19,2), event_private_event_id varchar(255), primary key (private_event_id)) engine=InnoDB
alter table event_ticket add constraint FKkxne9yawny3rurrd68nvllbj5 foreign key (event_private_event_id) references event (private_event_id)
create table event (private_event_id varchar(255) not null, created_at datetime, updated_at datetime, event_capacity integer, event_id varchar(255), event_name varchar(50), event_occupation integer, location varchar(20), time datetime, primary key (private_event_id)) engine=InnoDB
create table event_ticket (private_event_id varchar(255) not null, created_at datetime, updated_at datetime, age integer, event_name varchar(255), event_ticket_id varchar(255), name varchar(20), surname varchar(20), ticket_name varchar(255), ticket_price decimal(19,2), event_private_event_id varchar(255), primary key (private_event_id)) engine=InnoDB
alter table event_ticket add constraint FKkxne9yawny3rurrd68nvllbj5 foreign key (event_private_event_id) references event (private_event_id)
create table event (private_event_id varchar(255) not null, created_at datetime, updated_at datetime, event_capacity integer, event_id varchar(255), event_name varchar(50), event_occupation integer, location varchar(20), time datetime, primary key (private_event_id)) engine=InnoDB
create table event_ticket (private_event_id varchar(255) not null, created_at datetime, updated_at datetime, age integer, event_name varchar(255), event_ticket_id varchar(255), name varchar(20), surname varchar(20), ticket_name varchar(255), ticket_price decimal(19,2), event_private_event_id varchar(255), primary key (private_event_id)) engine=InnoDB
alter table event_ticket add constraint FKkxne9yawny3rurrd68nvllbj5 foreign key (event_private_event_id) references event (private_event_id)
create table event (private_event_id varchar(255) not null, created_at datetime, updated_at datetime, event_capacity integer, event_id varchar(255), event_name varchar(50), event_occupation integer, location varchar(20), time datetime, primary key (private_event_id)) engine=InnoDB
create table event_ticket (private_event_id varchar(255) not null, created_at datetime, updated_at datetime, age integer, event_name varchar(255), event_ticket_id varchar(255), name varchar(20), surname varchar(20), ticket_name varchar(255), ticket_price decimal(19,2), event_private_event_id varchar(255), primary key (private_event_id)) engine=InnoDB
alter table event_ticket add constraint FKkxne9yawny3rurrd68nvllbj5 foreign key (event_private_event_id) references event (private_event_id)
create table event (private_event_id varchar(255) not null, created_at datetime, updated_at datetime, event_capacity integer, event_id varchar(255), event_name varchar(50), event_occupation integer, location varchar(20), time datetime, primary key (private_event_id)) engine=InnoDB
create table event_ticket (private_event_id varchar(255) not null, created_at datetime, updated_at datetime, age integer, event_name varchar(255), event_ticket_id varchar(255), name varchar(20), surname varchar(20), ticket_name varchar(255), ticket_price decimal(19,2), event_private_event_id varchar(255), primary key (private_event_id)) engine=InnoDB
alter table event_ticket add constraint FKkxne9yawny3rurrd68nvllbj5 foreign key (event_private_event_id) references event (private_event_id)
create table event (private_event_id varchar(255) not null, created_at datetime, updated_at datetime, event_capacity integer, event_id varchar(255), event_name varchar(50), event_occupation integer, location varchar(20), time datetime, primary key (private_event_id)) engine=InnoDB
create table event_ticket (private_event_id varchar(255) not null, created_at datetime, updated_at datetime, age integer, event_name varchar(255), event_ticket_id varchar(255), name varchar(20), surname varchar(20), ticket_name varchar(255), ticket_price decimal(19,2), event_private_event_id varchar(255), primary key (private_event_id)) engine=InnoDB
alter table event_ticket add constraint FKkxne9yawny3rurrd68nvllbj5 foreign key (event_private_event_id) references event (private_event_id)
create table event (private_event_id varchar(255) not null, created_at datetime, updated_at datetime, event_capacity integer, event_id varchar(255), event_name varchar(50), event_occupation integer, location varchar(20), time datetime, primary key (private_event_id)) engine=InnoDB
create table event_ticket (private_event_id varchar(255) not null, created_at datetime, updated_at datetime, age integer, event_name varchar(255), event_ticket_id varchar(255), name varchar(20), surname varchar(20), ticket_name varchar(255), ticket_price decimal(19,2), event_private_event_id varchar(255), primary key (private_event_id)) engine=InnoDB
alter table event_ticket add constraint FKkxne9yawny3rurrd68nvllbj5 foreign key (event_private_event_id) references event (private_event_id)
create table event (private_event_id varchar(255) not null, created_at datetime, updated_at datetime, event_capacity integer, event_id varchar(255), event_name varchar(50), event_occupation integer, location varchar(20), time datetime, primary key (private_event_id)) engine=InnoDB
create table event_ticket (private_event_id varchar(255) not null, created_at datetime, updated_at datetime, age integer, event_name varchar(255), event_ticket_id varchar(255), name varchar(20), surname varchar(20), ticket_name varchar(255), ticket_price decimal(19,2), event_private_event_id varchar(255), primary key (private_event_id)) engine=InnoDB
alter table event_ticket add constraint FKkxne9yawny3rurrd68nvllbj5 foreign key (event_private_event_id) references event (private_event_id)
